<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Benefit.Domain\Benefit.Domain.csproj" />
		<ProjectReference Include="..\Toolkit\Toolkit.csproj" />
		<PackageReference Include="Refit.HttpClientFactory" Version="6.3.2" />
    <PackageReference Include="MassTransit" Version="8.0.6" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.35" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.7" />
	</ItemGroup>

</Project>
